// <auto-generated />
namespace Groupe12Exam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class GOODMIGRATION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GOODMIGRATION));
        
        string IMigrationMetadata.Id
        {
            get { return "202503090137052_GOODMIGRATION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
